In [3]:
import numpy as np

5


### Initializing an array

In [8]:
pyArray = np.array([0, 1, 2, 3, 4])
print(pyArray)

[0 1 2 3 4]


### size, dimensions and shape
Shape: tuple of index that indicates the size of the array in each dimension


In [6]:
print(pyArray.size)
print(pyArray.ndim)
print(pyArray.shape)

5
1
(5,)


Like lists and tuples, we can split an array

## Basic Operations


### Vector adictions
This is very usefull to linear algebra

product of two numpy arrays is a multiplication over the elements in same component of the two arrays

`np.dot(u, v)` returns the escalar product over the arrays

In [18]:
u = np.array([1, 0])
v = np.array([0, 1])
a = np.array([2, 3, 5])
b = np.array([3, 1, 2])
w = u + v
print('w = u + v', end='\t')
print(w)
w = u - v
print('w = u - v', end='\t')
print(w)
w = u + 1
print('w = u + 1', end='\t')
print(w)
w = 2*u - v
print('w = 2*u - v', end='\t')
print(w)
w = u * v
print('w = u * v', end='\t')
print(w)
w = np.dot(a, b)
print('w = np.dot(a,b)', end='\t')
print(w)

w = u + v	[1 1]
w = u - v	[ 1 -1]
w = u + 1	[2 1]
w = 2*u - v	[ 2 -1]
w = u * v	[0 0]
w = np.dot(a,b)	19


## Universal Functions

### Mean, max, constant pi, sin, cos

In [25]:
mean = a.mean()
print(mean)
max = a.max()
print(max)
print(np.pi)
print(np.sin(np.pi / 2))

3.3333333333333335
5
3.141592653589793
1.0


### linespace

In [26]:
np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

# Two dimensions numpy

In [31]:
pyArray = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(pyArray)
print(f'shape: {pyArray.shape}')
print(f'size: {pyArray.size}')

[[11 12 13]
 [21 22 23]
 [31 32 33]]
shape: (3, 3)
size: 9


In [40]:
print(pyArray[0:3,1:3])
print()
print(pyArray[:2,:2])

[[12 13]
 [22 23]
 [32 33]]

[[11 12]
 [21 22]]
